<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAJIDs-MBP.fios-router.home" ignored="0" name="Test03" tests="5" failures="2" timestamp="2021-05-26T04:32:05 EDT" time="0.007" errors="0">
  <testcase name="checkoutTest" time="0.001" classname="groupingTests.GroupingTest3">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at groupingTests.GroupingTest3.checkoutTest(GroupingTest3.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkoutTest -->
  <testcase name="featuresTest" time="0.0" classname="groupingTests.GroupingTest3"/>
  <testcase name="loginTest" time="0.0" classname="groupingTests.GroupingTest3"/>
  <testcase name="productTest" time="0.0" classname="groupingTests.GroupingTest3"/>
  <testcase name="trackingTest" time="0.0" classname="groupingTests.GroupingTest3">
    <failure type="java.lang.AssertionError" message="expected [9] but found [8]">
      <![CDATA[java.lang.AssertionError: expected [9] but found [8]
at groupingTests.GroupingTest3.trackingTest(GroupingTest3.java:33)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- trackingTest -->
</testsuite> <!-- Test03 -->
